<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RolesSeeder extends Seeder
{
    public function run(): void
    {
        $roles = [
            // Internal Staff Roles (11 Roles)
            [
                'id' => 'ROLE_PRACTICE_OWNER',
                'name' => 'Practice Owner',
                'description' => 'Practice owner with full system access',
                'hierarchy_level' => 1,
                'is_staff' => true,
                'is_provider' => false,
                'is_external' => false,
                'color' => '#DC2626',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ROLE_PRACTICE_ADMIN',
                'name' => 'Practice Administrator',
                'description' => 'System administrator with near-full access',
                'hierarchy_level' => 1,
                'is_staff' => true,
                'is_provider' => false,
                'is_external' => false,
                'color' => '#B91C1C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ROLE_PRACTICE_MANAGER',
                'name' => 'Practice Manager',
                'description' => 'Operations manager with administrative and financial access',
                'hierarchy_level' => 2,
                'is_staff' => true,
                'is_provider' => false,
                'is_external' => false,
                'color' => '#EA580C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ROLE_DENTIST',
                'name' => 'Dentist/Provider',
                'description' => 'Licensed dentist providing clinical services',
                'hierarchy_level' => 2,
                'is_staff' => true,
                'is_provider' => true,
                'is_external' => false,
                'color' => '#2563EB',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ROLE_HYGIENIST',
                'name' => 'Dental Hygienist',
                'description' => 'Licensed hygienist providing preventive services',
                'hierarchy_level' => 3,
                'is_staff' => true,
                'is_provider' => true,
                'is_external' => false,
                'color' => '#059669',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ROLE_DENTAL_ASSISTANT',
                'name' => 'Dental Assistant',
                'description' => 'Assistant supporting clinical procedures',
                'hierarchy_level' => 3,
                'is_staff' => true,
                'is_provider' => false,
                'is_external' => false,
                'color' => '#0891B2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ROLE_FRONT_DESK',
                'name' => 'Front Desk/Receptionist',
                'description' => 'Front office staff managing appointments and patient flow',
                'hierarchy_level' => 3,
                'is_staff' => true,
                'is_provider' => false,
                'is_external' => false,
                'color' => '#7C3AED',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ROLE_BILLING_SPECIALIST',
                'name' => 'Billing Specialist',
                'description' => 'Financial specialist managing billing and insurance',
                'hierarchy_level' => 2,
                'is_staff' => true,
                'is_provider' => false,
                'is_external' => false,
                'color' => '#CA8A04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ROLE_INSURANCE_COORDINATOR',
                'name' => 'Insurance Coordinator',
                'description' => 'Specialist focused on insurance operations',
                'hierarchy_level' => 3,
                'is_staff' => true,
                'is_provider' => false,
                'is_external' => false,
                'color' => '#D97706',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ROLE_LAB_TECHNICIAN',
                'name' => 'Lab Technician',
                'description' => 'Technician managing lab cases (can be external)',
                'hierarchy_level' => 4,
                'is_staff' => false,
                'is_provider' => false,
                'is_external' => true,
                'color' => '#64748B',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ROLE_MARKETING_COORDINATOR',
                'name' => 'Marketing Coordinator',
                'description' => 'Marketing specialist managing patient outreach',
                'hierarchy_level' => 3,
                'is_staff' => true,
                'is_provider' => false,
                'is_external' => false,
                'color' => '#DB2777',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // External User Roles (2 Roles)
            [
                'id' => 'ROLE_PATIENT',
                'name' => 'Patient',
                'description' => 'Patient with access to own records via portal',
                'hierarchy_level' => 5,
                'is_staff' => false,
                'is_provider' => false,
                'is_external' => true,
                'color' => '#6B7280',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'ROLE_REFERRING_PROVIDER',
                'name' => 'Referring Provider',
                'description' => 'External specialist receiving referrals',
                'hierarchy_level' => 5,
                'is_staff' => false,
                'is_provider' => true,
                'is_external' => true,
                'color' => '#4B5563',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('roles')->insert($roles);
    }
}
